### ISSUE TITLE
My 2 cents...

### ISSUE THREAD

**Issue by FDelporte** [Pi4J/pi4j-logo#2]
Version 5 with a small border looks best for me, would like to see that one also in the transparent version on a light and dark background. 

Maybe also with a more "serious" font? I tried some with https://wordmark.it

<img width="247" alt="Screenshot 2021-09-16 at 20 34 15" src="https://user-images.githubusercontent.com/1415873/133666431-c1fccbfb-3758-40e4-8119-b992602e6143.png">
<img width="312" alt="Screenshot 2021-09-16 at 20 33 50" src="https://user-images.githubusercontent.com/1415873/133666435-f36ee9ba-1b66-41c6-821e-cc66a1a9f5ca.png">
<img width="273" alt="Screenshot 2021-09-16 at 20 33 28" src="https://user-images.githubusercontent.com/1415873/133666436-f651b9e0-d047-43ec-be73-99775dec780b.png">
/

**Comment by HanSolo** [comment]
Yep…tried already lots of fonts but can try more serious onces 👍🏻

**Comment by FDelporte** [comment]
I like the font of V7!
