### ISSUE TITLE
V7 alternative with Pi4J instead of PI4J

### ISSUE THREAD

**Issue by FDelporte** [Pi4J/pi4j-logo#3]
I see on the raspberrypi.com website, they consistently use Pi with lower i. Maybe we should do the same?

**Comment by HanSolo** [comment]
No problem, will change that

**Comment by HanSolo** [comment]
Replaced the capital 'I' with 'i' in version 7 with commit dd6ee4a9a18b23f70d0ff20fbd2a4ca35d9f6101

**Comment by FDelporte** [comment]
can you do the same with version 5 with small border?
thanks!

and then we go for final voting round ;-)

**Comment by HanSolo** [comment]
Done with commit edd4d05522e6d3349a25220a7899b9d15b7b51f5

**Comment by FDelporte** [comment]
thanks a lot!!
